export const ErrorCodes = {
  // Auth & Tenant
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',

  // Project & Domain
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  ENVIRONMENT_NOT_FOUND: 'ENVIRONMENT_NOT_FOUND',
  TOPOLOGY_INVALID: 'TOPOLOGY_INVALID',
  SYNCHRONOUS_CYCLE_DETECTED: 'SYNCHRONOUS_CYCLE_DETECTED',

  // Scenario & Versioning
  SCENARIO_VERSION_CONFLICT: 'SCENARIO_VERSION_CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // Run Execution & Admission
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  RUN_INVALID_STATE: 'RUN_INVALID_STATE',
  RUN_ADMISSION_DENIED: 'RUN_ADMISSION_DENIED',
  RUN_LEASE_STALE: 'RUN_LEASE_STALE',

  // Simulation Core
  SIM_CONFIG_INVALID: 'SIM_CONFIG_INVALID',
  SIM_CHECKPOINT_CORRUPT: 'SIM_CHECKPOINT_CORRUPT',
  SIM_EVENT_LOOP_LIMIT: 'SIM_EVENT_LOOP_LIMIT',
  SIM_STATE_HASH_MISMATCH: 'SIM_STATE_HASH_MISMATCH',
  SIM_RESOURCE_EXHAUSTED: 'SIM_RESOURCE_EXHAUSTED',
  SIM_CANCELLED: 'SIM_CANCELLED',
  SIM_INTERNAL: 'SIM_INTERNAL',

  // Validation & Calibration
  VALIDATION_TARGET_NOT_ALLOWED: 'VALIDATION_TARGET_NOT_ALLOWED',
  VALIDATION_APPROVAL_REQUIRED: 'VALIDATION_APPROVAL_REQUIRED',
  CALIBRATION_OVERFIT: 'CALIBRATION_OVERFIT',
  REPORT_DATASET_MISSING: 'REPORT_DATASET_MISSING',

  // System & Infrastructure
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
